# Generated by Django 3.1.2 on 2020-11-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcontroluser',
            name='First name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='costcontroluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
