# Generated by Django 3.1.2 on 2020-11-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendings',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
